#!/bin/sh
# Author: rDini
######################### VARIABLES

DefMonitor="LVDS1"
DefaultPosition="--left-of"

MONITOR2=$(xrandr |grep " connected" | awk '{if($2 !~ "disconnected"){print $1}}' |grep -v $DefMonitor | head -n 1)

############ FUNCTIONS ###############
function moveMonitor(){
        echo "Second monitor: $MONITOR2"
        CMD="xrandr --output $MONITOR2 --auto $1 $DefMonitor"
        echo "Running command: $CMD"
        eval $CMD
}
printusage(){
	echo -e "Usage help: \n
	\t-l\t Move second monitor to 'left of' main monitor
	\t-r\t Move second monitor to 'right of' main monitor
	\t-t\t Move second monitor to 'above of' main monitor
	\t-b\t Move second monitor to 'bellow of' main monitor"
}
####################################################################
if [ -z $MONITOR2 ] ; then
	xrandr --output $DefMonitor --auto
	exit
fi
################## ---------- MENU
if
        [ -z $1 ]
then
       echo -e "Second monitor: $MONITOR2 \t Default: $DefaultPosition"
       cmd="xrandr --output $MONITOR2 --auto $DefaultPosition $DefMonitor"
       echo "Running command: $cmd"
       eval $cmd
else
	while getopts ":htlrb" opt; do
	  case $opt in
	        \?)     echo -e "Invalid option: $OPTARG\n" ; printusage ; exit 1 ;;
	        h)      printusage ;;
		t)	moveMonitor --above ;;
                l)      moveMonitor --left-of ;;
                r)      moveMonitor --right-of ;;
                b)      moveMonitor --below ;;
		:)      echo "Option -$OPTARG requires an argument." >&2
	                exit 1 ;;
	  esac
	done
fi
