#!/bin/sh
# Author: rDini

#f [ $(xrandr | grep -A 1 " connected " | grep -v "^--$" | awk '{print $1}' | grep -c HDMI1) ] ; then
#	cmd="xrandr --output HDMI1 --auto --left-of LVDS1"
#	echo "Running command: $cmd"
#	eval $cmd
#fi

MONITOR=$(xrandr |grep " connected" | awk '{if($2 !~ "disconnected"){print $1}}' |grep -v LVDS1 | head -n 1)
echo "Second monitor: $MONITOR"
       cmd="xrandr --output $MONITOR --auto --above LVDS1"
       echo "Running command: $cmd"
       eval $cmd

